#!/bin/sh

target_pane=$1
[ -n "$target_pane" ] || exit 0
[ -x "$HOME/.tmux/window-name" ] || exit 0

pane_active=$(tmux display-message -p -t "$target_pane" '#{pane_active}' 2>/dev/null) || exit 0
[ "$pane_active" = 1 ] || exit 0

window_id=$(tmux display-message -p -t "$target_pane" '#{window_id}' 2>/dev/null) || exit 0
automatic_rename=$(tmux show-options -A -v -w -t "$window_id" automatic-rename 2>/dev/null) || exit 0
[ "$automatic_rename" = on ] || exit 0

directory=$(tmux display-message -p -t "$target_pane" '#{pane_current_path}' 2>/dev/null) || exit 0
project_name=$("$HOME/.tmux/window-name" "$directory" '')

if [ -n "$project_name" ]; then
    rename_format=$(printf '%s' "$project_name" | sed 's/#/##/g')
    window_name=$project_name
else
    rename_format='#{pane_current_command}'
    window_name=$(tmux display-message -p -t "$target_pane" '#{pane_current_command}' 2>/dev/null) || exit 0
fi
[ -n "$window_name" ] || exit 0

tmux set-window-option -t "$window_id" automatic-rename-format "$rename_format" \; \
    rename-window -t "$window_id" "$window_name" \; \
    set-window-option -t "$window_id" automatic-rename on 2>/dev/null
